### ISSUE TITLE
Bug: Path matching fails when the URL contains encoded parts

### ISSUE THREAD

**Issue by chrischu** [WireMock-Net/WireMock.Net#178] opened 2018-08-10 13:11 UTC
When setting up a path matcher with a string containing URL-encoded values (e.g. `Request.Create().UsingGet().WithPath("/path/a%20b")`) the path matching no longer works. When looking at the request log in the FluentMockServer one can see that the request found does have the unencoded request URL ("/path/a b" instead of "/path/a%20b") and therefore the match isn't successful.

This seems to be due to a problem with OWIN decoding the URL (see https://github.com/aspnet/AspNetKatana/issues/208). This bug seems to no longer exist when using ASP.NET Core instead of OWIN, so switching to ASP.NET Core hosting would be a way to fix it, albeit a pretty expensive one I assume.

**Comment by chrischu** [comment] 2018-08-12 19:25
Mhh I created a repro sample with .NET 4.7.2 that reproduces the problem: In the program I call the URL "/A%2fB" but WireMock.Net logs the call as "/A/B". When looking at the loaded modules in Debug mode it is also plainly visible that OWIN is used:
![image](https://user-images.githubusercontent.com/447251/44005602-2210707c-9e76-11e8-8045-b85d17bbf674.png)

Am I doing something wrong?


[WireMockRepro.zip](https://github.com/WireMock-Net/WireMock.Net/files/2281258/WireMockRepro.zip)

**Comment by StefH** [comment] 2018-08-13 06:37
> Currently OWIN is used for net452.
And because net 4.6.x and net 4.7.x fallback to this framework, the OWIN code is also used in your application.

I did a quick test with net 461, and it seems I can use the latest Microsoft.AspNetCore (version 2.x.x) there.

So I'll update WireMock.Net to use Microsoft.AspNetCore from 4.6.1 and up.

And for net452, maybe apply a hotfix / patch?

**Comment by StefH** [comment] 2018-08-16 05:58
I fixed the code to use `Microsoft.AspNetCore` (for net461 and up) and I tried to reproduce your problem with these tests:

``` c#
[Fact] //: TODO : this test fails???
public void Request_WithPath_EncodedSpaces()
{
    // Assign
    var spec = Request.Create().WithPath("/path/a b").UsingAnyMethod();

    // when
    var body = new BodyData();
    var request = new RequestMessage(new UrlDetails("http://localhost/path/a%2fb"), "GET", ClientIp, body);

    // then
    var requestMatchResult = new RequestMatchResult();
    Check.That(spec.GetMatchingScore(request, requestMatchResult)).IsEqualTo(1.0);
}

[Fact]
public void Request_WithPath_Spaces()
{
    // Assign
    var spec = Request.Create().WithPath("/path/a b").UsingAnyMethod();

    // when
    var body = new BodyData();
    var request = new RequestMessage(new UrlDetails("http://localhost/path/a b"), "GET", ClientIp, body);

    // then
    var requestMatchResult = new RequestMatchResult();
    Check.That(spec.GetMatchingScore(request, requestMatchResult)).IsEqualTo(1.0);
}
```

However I need some help from you to give me correct examples + expectations. Because now the `Request_WithPath_EncodedSpaces` still fails.

**Comment by chrischu** [comment] 2018-08-16 07:51
Cool!

I think that `Request_WithPath_EncodedSpaces` fails is to be expected. I don't expect it to work. The only case I expect to work is when at both ends the space is encoded (or not encoded), like this:
```
[Fact]
public void Request_WithPath_EncodedSpaces()
{
    // Assign
    var spec = Request.Create().WithPath("/path/a%2fb").UsingAnyMethod();

    // when
    var body = new BodyData();
    var request = new RequestMessage(new UrlDetails("http://localhost/path/a%2fb"), "GET", ClientIp, body);

    // then
    var requestMatchResult = new RequestMatchResult();
    Check.That(spec.GetMatchingScore(request, requestMatchResult)).IsEqualTo(1.0);
}
```

**Comment by StefH** [comment] 2018-08-16 17:58
https://github.com/WireMock-Net/WireMock.Net/pull/185

**Comment by StefH** [comment] 2019-07-12 11:00
Closing

**Closed by StefH** 2019-07-12 11:00 UTC
Labels: bug, question
