### ISSUE TITLE
Admin API fails to create a mapping with Request Body matching

### ISSUE THREAD

**Issue by yunj** [WireMock-Net/WireMock.Net#486] opened 2020-07-09 13:14 UTC
### Describe the bug
Admin API is used to create a mapping which has some sort of request body match, but other matches get created except body.

### Expected behavior:
Body match should appear when querying `GET __admin/mappings`.

### Test to reproduce
Admin API is used to create the following mapping.
``` c#
var model = new MappingModel
{
    Request = new RequestModel
    {
        Path = "test",
        Body = new BodyModel
        {
            Matcher = new MatcherModel
            {
                Name = "RegexMatcher",
                Pattern = "hello"
            }
        }
    },
    Response = new ResponseModel
    {
        Body = "world"
    }
};
await RestClient.For<IWireMockAdminApi>("http://localhost").PostMappingAsync(model);
```
The response from `GET __admin/mappings`
``` json
[
  {
    "Guid": "486b7f76-f29a-4928-9f16-bf6c3a2ce8f2",
    "Request": {
      "Path": {
        "Matchers": [
          {
            "Name": "WildcardMatcher",
            "Pattern": "test",
            "IgnoreCase": false
          }
        ]
      }
    },
    "Response": {
      "Body": "world"
    }
  }
]
```

**Comment by StefH** [comment] 2020-07-09 13:51
Thank you.
I'll investigate.

**Comment by StefH** [comment] 2020-07-09 18:19
@yunj 
The root cause is that you don't provide the Methods on you wish to match. The current code does not return the bodymatcher if there are no Methods defined or if the methods have a 'get'.

I'll investigate why I did add this check in the code.

For your solution now: set the Methods.

**Comment by StefH** [comment] 2020-07-09 19:37
https://github.com/WireMock-Net/WireMock.Net/pull/487

**Comment by StefH** [comment] 2020-07-09 19:38
Fixed.
New NuGet and Docker will be released soon.

**Closed by StefH** 2020-07-09 19:38 UTC
Labels: bug

**Comment by yunj** [comment] 2020-07-09 20:08
@StefH thanks very much for your quick fix.
