### ISSUE TITLE
Bug: Server not listening after Start() returns (on macOS)

### ISSUE THREAD

**Issue by benjamin-bader** [WireMock-Net/WireMock.Net#44] opened 2017-08-19 04:56 UTC
Hi, I just ported a project from .NET 4.5 to .NET Core 2.0 on macOS.  I noticed that a unit test using FluentMockServer started failing with `System.Net.Http.CurlException : Couldn't connect to server`.

When I add `Thread.Sleep(100)` after starting the server, the error goes away.  I'm assuming that, on macOS at least, the underlying server implementation is a bit more asynchronous than that on .NET proper (or on Mono).  I notice that `FluentMockServer.Start(...)` calls `StartAsync` on its inner HTTP server.  Is there a way to wait for that async start to finish that's more reliable than putting the test thread to sleep?

**Comment by StefH** [comment] 2017-08-19 08:29
Can you post the full code where you put the Thread.Sleep()?

**Comment by benjamin-bader** [comment] 2017-08-19 19:58
I can't post the actual source (proprietary, etc), but here's the essence.  It's an xunit test class:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using FluentAssertions;
using WireMock.RequestBuilders;
using WireMock.ResponseBuilders;
using WireMock.Server;
using Xunit;

namespace Service
{
    public class ServiceClientTest : IDisposable
    {
        private FluentMockServer server;
        private MyServiceClient client;

        public PowerLiftClientTest()
        {
            server = FluentMockServer.Start();
            client = new MyServiceClient(server.Urls.Select(u => new Uri(u)).First());
        }

        public void Dispose()
        {
            server.Dispose();
            client.Dispose();
        }
        
        [Fact]
        public async Task ClientRequestIsWellFormed()
        {
            var request = new ServiceRequest() { ... };

            // Request fails if we don't sleep here, because the server has not yet finished starting.
            Thread.Sleep(100);

            server.Given(Request.Create().WithPath("/api/endpoint").UsingPost())
                .RespondWith(Response.Create()
                    .WithStatusCode(200)
                    .WithBodyAsJson(new Dictionary<string, object>
                    {
                        ["id"]              = "requestId",
                        ["analysisId"]      = Guid.NewGuid()
                    }));

            var response = await client.PostIncidentAsync(request);

            Assert.NotNull(response);
        }
    }
}
```

**Comment by skunkworks** [comment] 2017-09-26 18:04
I can confirm that I've had the same issue with WireMock.NET not starting up the server in time on MacOS.

**Comment by StefH** [comment] 2017-09-26 21:14
Are you running on netcore 1.x or 2.0 ?

**Comment by skunkworks** [comment] 2017-09-26 21:26
@StefH This is on .NET Core 2.0.

**Comment by StefH** [comment] 2017-09-27 15:42
@skunkworks OK. Clear.

I was wondering if there is an environment setting to see if I'm running on Linux, Windows or MacOS...  I'll investigate this.

**Comment by benjamin-bader** [comment] 2017-09-27 17:14
What do you think about returning a `Task` in the public `FluentMockServer` API?  The inner HTTP server already seems to, but the server doesn't do anything with it.

Alternately, why not block on the task returned by the inner HTTP server?

**Comment by StefH** [comment] 2017-09-30 08:06
Should be fixed. Download source or use latest NuGet version `1.0.2.4-preview-02`.

**Comment by StefH** [comment] 2017-10-03 10:39
@benjamin-bader and @skunkworks : were you able to test this new source-code / NuGet ?

**Comment by skunkworks** [comment] 2017-10-03 22:51
We'll give it a shot and report back. Thanks for the fix!

**Comment by sdcoffey** [comment] 2017-10-05 18:16
@StefH looks like this update worked, thanks for the quick fix!

**Comment by StefH** [comment] 2017-10-11 15:35
@skunkworks : I close this issue now, if you have more troubles, create a new issue.

**Closed by StefH** 2017-10-11 15:35 UTC
Labels: bug
