### ISSUE TITLE
ParamMatcher failed when using parameter with comma

### ISSUE THREAD

**Issue by gigiogodoi** [WireMock-Net/WireMock.Net#849] opened 2022-11-23 23:09 UTC
### Describe the bug
I'm working on a system that consumes a 3rd party API which accepts as querystring a SQL statement.
For example, to query some data from any table just build the URI like this:
- `http://host/api/queryservice?query=SELECT id FROM table WHERE id = 1`
While trying to mock this API, I realized that whenever I tried to mock a statement using comma, the ParamMatcher fails.
For example, `SELECT id, value FROM table WHERE id = 1`.
And I received a 404 (NotFound) error code.

### Expected behavior:
I expected the ParamMatcher has succeded, and returned 200 (OK).

### Test to reproduce
1 - Create an API which receives as querystring a SQL statement
2 - Mock that API using "WithParam" function
3 - Test creating a statement which has a 'comma' within, "SELECT id, value FROM table WHERE id = 1"

### Other related info
Provide additional information if any.

**Comment by StefH** [comment] 2022-11-24 08:09
What you can try:

:one:
url-escape the comma

:two:
Set https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Settings/WireMockServerSettings.cs#L267 to `QueryParameterMultipleValueSupport.NoComma`

**Comment by gigiogodoi** [comment] 2022-11-24 19:17
Thanks for reply,

I've downloaded the latest nuget version (1.5.10) but there isn't this property.

![image](https://user-images.githubusercontent.com/35941336/203852552-14a9a4c5-e735-4ce0-97c9-68d0122e6de8.png)

Am I doing anything wrong?

**Comment by StefH** [comment] 2022-11-24 20:37
No. Nothing is wrong on your end 

I just realized that I need to release a new version which includes this.

I'll do that now.

**Comment by gigiogodoi** [comment] 2022-11-24 21:52
Thanks, @StefH

**Comment by StefH** [comment] 2022-11-25 07:14
It could be that Url escaping does indeed nor work.

Then you need to use option 2.

Can this issue be closed?

**Comment by gigiogodoi** [comment] 2022-11-25 11:16
I'm still facing the issue.

The API I'm trying to consume is this one:
https://docs.oracle.com/en/cloud/saas/service/18a/cxsvc/op-services-rest-connect-v1.4-queryresults-get.html

It's a public Oracle REST API, to query entities from database.

When I try to mock a return to this request I get an 404 error.

![image](https://user-images.githubusercontent.com/35941336/203974136-12a4861b-56e2-4f36-a681-1c362837b215.png)

**Comment by StefH** [comment] 2022-11-30 09:04
https://github.com/WireMock-Net/WireMock.Net/pull/854

**Comment by StefH** [comment] 2022-11-30 09:05
@gigiogodoi 
Can you please provide a full working c# code example which simulates your issue? Because I cannot reproduce it using unit tests.

**Comment by gigiogodoi** [comment] 2022-11-30 12:10
@StefH 
Follow an example repository to reproduce the error, using XUnit and .NET6 .

https://github.com/gigiogodoi/UnitTestWithWiremock

Inside it, there are 2 test cases, one failing because it is using a query with comma.

![image](https://user-images.githubusercontent.com/35941336/204792651-b67ed81f-6346-4874-8f36-cb4db0677336.png)

**Comment by StefH** [comment] 2022-11-30 14:36
Thanks a lot for this unit test. I did find the issue and it's fixed in preview version `1.5.10-ci-16744`.

**Comment by StefH** [comment] 2022-11-30 17:54
Yes.

Works fine.

https://github.com/WireMock-Net/WireMock.Net/blob/stef-849/test/WireMock.Net.Tests/WireMockServerTests.WithParam.cs

**Comment by StefH** [comment] 2022-12-02 09:39
@gigiogodoi Is it ok?

**Comment by StefH** [comment] 2022-12-03 10:03
I'll merge the PR.

**Closed by StefH** 2022-12-03 10:03 UTC
Labels: question

**Comment by gigiogodoi** [comment] 2022-12-03 11:53
I was not able to download the preview version, because it was not releated in the nuget package manager.

But I will try once you release a new version.

**Comment by StefH** [comment] 2022-12-03 12:58
previews are here: https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

But I'll release an official version today on nuget.
