### ISSUE TITLE
Exact byte array request matching fails on specific byte arrays

### ISSUE THREAD

**Issue by Archomeda** [WireMock-Net/WireMock.Net#601] opened 2021-04-12 15:36 UTC
### Describe the bug
Exact matching on byte arrays sometimes fails, depending on the byte array contents.

### Expected behavior:
Exact matching should succeed, no matter what the byte array contents are, as long as it's the same.

### Test to reproduce
The following code reproduces the bug:
```cs
static async Task Main(string[] args)
{
    await DoStuff(new byte[] { 201, 202, 203 });
    await DoStuff(new byte[] { 49, 50, 51 });
}

static async Task DoStuff(byte[] bytes)
{
    using var server = WireMockServer.Start();
    using var httpClient = new HttpClient { BaseAddress = new Uri(server.Urls[0]) };

    server
        .Given(Request.Create()
            .WithPath("/test")
            .WithBody(bytes)
            .UsingPost())
        .RespondWith(Response.Create()
            .WithSuccess()
            .WithBody("success"));

    using var content = new ByteArrayContent(bytes);
    var response = await httpClient.PostAsync("test", content);

    Console.WriteLine($"{response.StatusCode} - {await response.Content.ReadAsStringAsync()}");
}
```

The output:
```
OK - success
NotFound - {"Status":"No matching mapping found"}
```

### Other related info
From my limited debugging, I've noticed that the request log shows different behavior. In the first case, it shows that DetectedBodyType = Bytes, while in the second case it's DetectedBodyType = String. In both cases the DetectedBodyTypeFromContentType = Bytes.

I don't expect WireMock to transform a request to a string automatically and then fail to match because it expects a byte array.

**Comment by StefH** [comment] 2021-04-16 19:42
The different DetectedBodyType should not cause this error I think.

I'll take a look what's the root cause.

Thank you for noticing this issue.

**Comment by StefH** [comment] 2021-04-18 19:30
New version will be released soon.

**Closed by StefH** 2021-04-18 19:30 UTC
Labels: bug

**Comment by Archomeda** [comment] 2021-04-18 22:28
Cool, thanks! 👍
