### ISSUE TITLE
Loading mapping models with `JsonMatcher`  is not working correctly

### ISSUE THREAD

**Issue by cezarypiatekGC** [WireMock-Net/WireMock.Net#504] opened 2020-09-17 21:16 UTC
### Describe the bug
Loading mapping models with `JsonMatcher` for Body matcher from a file is not working correctly.

### Steps to reproduce:

1. Create mapping with JsonMatcher for the body and save it to file as follow

```cs
var requestBuilder = Request.Create()
	.WithPath("/api/v1.0/accounts/")
	.WithHeader("Content-Type", "application/json; charset=utf-8")
	.WithBody(new JsonMatcher(new { AccountIds = new[] { 1, 2, 3} }))
	.UsingPost();

var respondWithAProvider = wiremockServer.Given(requestBuilder, saveToFile: true);

var responseProvider = Response.Create()
	.WithStatusCode(200)
	.WithHeader("Content-Type", "application/json; charset=utf-8")
	.WithBody(JsonConvert.SerializeObject(new[] { 1, 2, 3 }));

wiremockServer.RespondWith(responseProvider);
```
2. As a result I get a file with the following content

```json
{
  "Guid": "7d1c7dcc-eba1-4c3a-bc82-0a444fe9fcd9",
  "Request": {
    "Path": {
      "Matchers": [
        {
          "Name": "WildcardMatcher",
          "Pattern": "/api/v1.0/accounts/",
          "IgnoreCase": false
        }
      ]
    },
    "Methods": [
      "POST"
    ],
    "Headers": [
      {
        "Name": "Content-Type",
        "Matchers": [
          {
            "Name": "WildcardMatcher",
            "Pattern": "application/json; charset=utf-8",
            "IgnoreCase": true
          }
        ]
      }
    ],
    "Body": {
      "Matcher": {
        "Name": "JsonMatcher",
        "Pattern": {
          "AccountIds": [1, 2, 3]
        },
        "IgnoreCase": false
      }
    }
  },
  "Response": {
    "StatusCode": 200,
    "BodyDestination": "SameAsSource",
    "Body": "[1,2,3]",
    "Headers": {
      "Content-Type": "application/json; charset=utf-8"
    }
  }
}
```

3. Load mapping from file and feed it to the WireMock server

```cs
var content = File.ReadAllText(@"__admin\mappings\7d1c7dcc-eba1-4c3a-bc82-0a444fe9fcd9.json");
wiremockServer.WithMapping(content);
```

### Expected behavior:
This is how `requestBuilder` looks like before saving mapping to a file
![image](https://user-images.githubusercontent.com/52414058/93528162-33c21c00-f93a-11ea-9bf9-669896447d9c.png)

This is how `requestBuilder` looks like after loading from a file

![image](https://user-images.githubusercontent.com/52414058/93528327-7552c700-f93a-11ea-8b5b-e88128f481b7.png)

The expectation is that the JsonMatcher works in the same way when loaded from a file and when created from the code. Currently, the pattern is always set to null when loading from a file.

### Other notes
This is probably caused by this line where every pattern is cast to string (non-string values will result with a `null`)
https://github.com/WireMock-Net/WireMock.Net/blob/7abf56eafaf9d57aff1234bf7c0ad0f408bb18d6/src/WireMock.Net/Serialization/MatcherMapper.cs#L39

**Comment by StefH** [comment] 2020-09-19 08:10
Hello @cezarypiatekGC . Thank you for your research.

I think the cause is that when serializing your example, the json file should contain the Pattern as a string:
``` js
"Body": {
      "Matcher": {
        "Name": "JsonMatcher",
        "Pattern": "{ \"AccountIds\": [1, 2, 3] }",
        "IgnoreCase": false
      }
    }
```

**Comment by StefH** [comment] 2020-09-19 08:49
#505 

@cezarypiatekGC : can you try preview version from MyGet : `WireMock.Net.1.2.18-ci-13750.nupkg` ?

**Comment by cezarypiatekGC** [comment] 2020-09-19 11:17
I've tested this preview package and there's still a difference between JsonMatcher before saving to file and after loading which affects how the matcher works.

Before saving to file

![image](https://user-images.githubusercontent.com/52414058/93665865-33309f00-fa7a-11ea-91f3-77add88ee361.png)

After loading from a file

![image](https://user-images.githubusercontent.com/52414058/93665889-4c395000-fa7a-11ea-8c25-bbb06f7a2120.png)

JObject vs JArray

**Comment by StefH** [comment] 2020-09-19 12:03
Can you try new version `WireMock.Net.1.2.18-ci-13754.nupkg` (or higher)?

**Comment by cezarypiatekGC** [comment] 2020-09-19 12:53
I've tried with WireMock.Net.1.2.18-ci-13754 but still, JsonMatcher has a different value and It's not working in the same way as it worked before saving to a file.

![image](https://user-images.githubusercontent.com/52414058/93667584-6fb6c780-fa87-11ea-8ee0-07524d532a6b.png)

**Comment by StefH** [comment] 2020-09-20 09:08
Note that the `Value` property will not be the same, because in your initial code this is an anonymous object. And when the mapping is read from a .json file, this is a JObject. But the `_valueAsJToken` is used for matching, and this should be the same.

So can you make a full example (unit test) which demonstrates your issue?

**Comment by cezarypiatekGC** [comment] 2020-09-21 21:15
Ok, I will try to prepare a test or demo app that reproduces that problem.

**Comment by RiccoFerraro** [comment] 2020-09-29 20:25
Hi guys, I also believe I'm having this problem. I have static mappings (generated via recording with wiremock.net) I just upgraded to 1.3.0. I've debugged into JsonMatcher and it appears `_valueAsJToken` is always a jtoken for a null object.
![image](https://user-images.githubusercontent.com/13544830/94611423-8fec4080-0256-11eb-948c-1f2f7f85659a.png)
 Not sure what I'm doing wrong here, but I feel like I've tried a million different things. 
![image](https://user-images.githubusercontent.com/13544830/94611566-c2963900-0256-11eb-85fc-c02de923c394.png). Any ideas on what could be the fix? Again, this Mapping is generated by recording with wiremock in code (in a different test execution by specifying: 
![image](https://user-images.githubusercontent.com/13544830/94611749-0ab55b80-0257-11eb-9c5e-608f9477df37.png)

The wiremock server which serves the static files is setup like this: 
![image](https://user-images.githubusercontent.com/13544830/94611872-31739200-0257-11eb-90da-c7c186e64730.png)

**Comment by StefH** [comment] 2020-09-30 06:23
Hello @RiccoFerraro,

The 1.3.0 version does not have any preview fixed code for this issue, in order to test that you need MyGet version `WireMock.Net.1.2.18-ci-13754.nupkg`.

And can you create a full working example please?

**Comment by RiccoFerraro** [comment] 2020-09-30 15:40
Hi @StefH Will do. I'll get back to you on if the issue is in that alpha build

**Comment by StefH** [comment] 2020-10-07 18:28
Hello @RiccoFerraro,did you have time yet to verify ?

**Comment by RiccoFerraro** [comment] 2020-10-07 18:30
@StefH Sorry I haven't had a chance yet. I will try to take a look at this sometime this week. I'll post here when I've tried it.

**Comment by RiccoFerraro** [comment] 2020-10-12 18:22
@StefH Sorry for the delay, still haven't had a chance to test this fix out yet. I've been absolutely slammed with work and will get to it as soon as I get a second to breath. On a related note, I did notice something else about partial match scores that seemed off. (probably requires a little redesign). For our team to continue using wiremock.net we need to trust that the Http VERB is ALWAYS respected. I've been noticing that, even when a post call is fired, Get matches are being favored (given higher scores) over POST calls (in this case because of the bug mentioned above, the POST call has a lower score because it is failing to match on the body matcher). This seems off. It should match on the highest score, for only a single verb type. I can't imagine a scenario where someone is okay with a get request being returned for a post call in an integration test??? That would be a broken integration test to me. Can we introduce a flag to strictly enforce just the verb?

**Comment by StefH** [comment] 2020-10-12 18:43
@RiccoFerraro Thanks about your remark about the Http VERB. I did create a new Issue for this, and I'll take a look how to fix this.

**Comment by StefH** [comment] 2020-10-14 10:57
@RiccoFerraro Investigating + solving that Http Method issue will take some more time.

Are you able to verify this issue ?
Else I will just create a new version because some code is also verified by https://github.com/WireMock-Net/WireMock.Net/issues/513

**Comment by RiccoFerraro** [comment] 2020-10-14 15:48
Hi @StefH, thanks for being so responsive. I'm sorry I don't have time to create test projects and try the all the different versions this week. What I can do is pull down the version in https://github.com/WireMock-Net/WireMock.Net/issues/513 and see if the problems I was having with post body matching are fixed. After that seems to work, I'll work on setting "ParitalMapping" to false to enforce strict mapping. Question, is it in an official nuget.org version? I can't use my-get outside of POC's.

**Comment by StefH** [comment] 2020-10-14 18:20
Hello @RiccoFerraro , I'll release a new version with this fix tonight and for now close this issue.

In case you have another problem please create a new issue.

**Closed by StefH** 2020-10-14 18:20 UTC
Labels: bug

**Comment by RiccoFerraro** [comment] 2020-12-11 19:43
Hi @StefH Quick question, What is the expected behavior for record playback for repeated calls to the same endpoint with these settings in 1.3.7? I'm wiremock doesn't seem to actually proxy the second call to the same endpoint, and instead is serving it's recorded response. This is a problem, because the expected behavior of the endpoint in question is that it changes between calls and i need to capture both responses. I have verified this by calling the endpoint directly in postman (with and without the wiremock server base url) and I get different responses
![image](https://user-images.githubusercontent.com/13544830/101947730-cb37b380-3ba5-11eb-83a2-c1503b12e471.png)

**Comment by StefH** [comment] 2020-12-12 07:48
@RiccoFerraro 
Did you already try "SaveMapping" = false and "SaveMappingToFile" = true ?
